{
 "title": "Memory Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "T12 - Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_free_bytes*100)/nvidia_smi_memory_total_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Box - Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_free_bytes*100)/nvidia_smi_memory_total_bytes{instance=\"10.200.0.198:9835\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "T12 - GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Box - GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_decoder_ratio{instance=\"10.200.0.198:9835\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}